#!/bin/bash

DIR=$HOME/Pictures/Wallpapers/
PICS=($(ls ${DIR}))

RANDOMPICS=${PICS[ $RANDOM % ${#PICS[@]} ]}

if [[ $(pidof swaybg) ]]; then
  pkill swaybg
fi

#change-wallpaper using swaybg
swaybg -i ${DIR}/${RANDOMPICS} -m fill &


